remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  week_1: https://mattdevigili.github.io/dms-smm695/week-1/
  week_2: https://mattdevigili.github.io/dms-smm695/week-2/
  week_3: https://mattdevigili.github.io/dms-smm695/week-3/
  week_4: https://mattdevigili.github.io/dms-smm695/week-4/
  week_5: https://mattdevigili.github.io/dms-smm695/week-5/
  week_6: https://mattdevigili.github.io/dms-smm695/week-6/